/* GENERATED by tools/gen_factory_bank.mjs — do not edit.
 *
 * OneTrick CHONK's 9 factory sounds (Punk Labs LLC, GPL-3.0-or-later),
 * converted from src/presets/factory/*.preset. Values are in DISPLAY units and
 * in PARAMS[] order; regenerate after any change to PARAMS[] or the .preset
 * files.
 */
#ifndef CHONK_FACTORY_BANK_H
#define CHONK_FACTORY_BANK_H

#define CHONK_FACTORY_PARAMS 28

typedef struct {
    const char *name;
    const char *desc;
    float value[CHONK_FACTORY_PARAMS];
} chonk_preset_t;

static const chonk_preset_t CHONK_FACTORY[] = {
    {"J-Bass", "It's like the P-Bass, but a different letter.", {
        68.0f, 100.0f, 50.0f, 0.0f, 40.0000f, 23.2500f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 2.0f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 35.0f, 1.0f, 0.0f, 100.0f, 0.0f
    }},
    {"Defender", "Defender of the bass.", {
        15.0500f, 100.0f, 50.0f, 0.0f, 50.0f, 72.7500f, 0.0f, 0.0f, 0.0f, 70.5000f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 2.0f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 35.0f, 1.0f, 0.0f, 100.0f, 0.0f
    }},
    {"Demonster", "The preset used in the demo song", {
        50.0f, 92.0f, 50.0f, 10.0000f, 68.7500f, 62.5000f, 0.0f, 0.0f, 0.0f, 37.5000f, 0.0f, 0.0f, 0.0f, 3.3600f, 0.0f, 0.0f, 1.0f, 2.0f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 35.0f, 1.0f, 0.0f, 100.0f, 0.0f
    }},
    {"Disco", "Maybe a funk bass would mask all that cringe?", {
        30.0000f, 100.0f, 50.0f, 12.0000f, 70.0f, 22.5000f, 0.0f, 0.0f, 0.0f, 38.5000f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 2.0f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 35.0f, 1.0f, 0.0f, 100.0f, 0.0f
    }},
    {"Flatworm", "Flat wound strings, but with terrible branding.", {
        70.5000f, 100.0f, 0.0f, 0.0f, 34.7500f, 50.0f, 0.0f, 0.0f, 0.0f, 14.0000f, 0.0f, 0.0f, 0.0f, -1.5600f, 0.0f, 0.0f, 1.0f, 2.0f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 35.0f, 1.0f, 0.0f, 100.0f, 0.0f
    }},
    {"Gargantuan", "A chonky rumble from down in the deeep.", {
        100.0f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -6.0000f, -12.0f, -12.0f, 0.0f, 1.0f, 2.0f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 35.0f, 1.0f, 0.0f, 100.0f, 0.0f
    }},
    {"Justice", "Get ready to ignite.", {
        0.0f, 73.2500f, 50.0f, 19.5000f, 77.0000f, 81.0f, 0.0f, 0.0f, 0.0f, 66.7500f, 0.0f, 0.0f, 0.0f, 7.1400f, 0.0f, 0.0f, 1.0f, 2.0f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 35.0f, 1.0f, 0.0f, 100.0f, 0.0f
    }},
    {"New Strings", "It's been literally 15 years", {
        34.0000f, 100.0f, 100.0f, 17.2500f, 50.0f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 2.0f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 35.0f, 1.0f, 0.0f, 100.0f, 0.0f
    }},
    {"Sitcom", "Just a slap about nothing", {
        37.5000f, 100.0f, 76.7500f, 65.5000f, 77.7500f, 100.0f, 0.0f, 0.0f, 0.0f, 22.0000f, 0.0f, 2.4000f, -3.0000f, 1.3200f, 1.3200f, 0.0f, 1.0f, 2.0f, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f, 35.0f, 1.0f, 0.0f, 100.0f, 0.0f
    }},
};

#define CHONK_FACTORY_COUNT ((int)(sizeof(CHONK_FACTORY) / sizeof(CHONK_FACTORY[0])))

#endif /* CHONK_FACTORY_BANK_H */
