/* Compile Punk Labs' factory .preset files into src/dsp/factory_bank.h.
 *
 *   node tools/gen_factory_bank.mjs        (run by scripts/build.sh)
 *
 * The 9 factory sounds ship with OneTrick CHONK as JSON files keyed by the
 * DISPLAY names its egui UI used ("Bass Pickup Position"). The module stores
 * the same numbers under Schwung keys ("pickup"), so this maps one to the
 * other ONCE, here, and emits a table in PARAMS[] order.
 *
 * Generated rather than hand-copied for the usual reason: the order is
 * PARAMS[]'s, and a hand-written table would go on compiling perfectly after
 * a param is inserted while loading every value one slot out.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..");

/* Schwung key -> the name Punk Labs' preset files use. A key absent from this
 * map (the articulation latches, which are performance state) keeps its
 * default and is skipped by load_preset. */
const UPSTREAM_NAME = {
  pickup:   "Bass Pickup Position",
  sustain:  "Bass Sustain",
  bright:   "Bass String Brightness",
  strike:   "Bass Strike Hardness",
  thump:    "Bass Thump",
  tone:     "Bass Tone Knob",
  gain:     "Mix Gain",
  pan:      "Mix Pan",
  sat:      "Mix Saturation",
  eq1:      "EQ Band 1",
  eq2:      "EQ Band 2",
  eq3:      "EQ Band 3",
  eq4:      "EQ Band 4",
  eq5:      "EQ Band 5",
  fine:     "MIDI Fine Tune",
  at_range: "MIDI Aftertouch Range",
  pw_range: "MIDI PitchWheel Range",
  sens:     "MIDI Sensitivity",
};

/* Read PARAMS[] out of the wrapper: key, min, max, default. One source of
 * truth for the order, the clamp and the fallback. */
const wrapper = readFileSync(join(repo, "src", "dsp", "chonk_plugin.cpp"), "utf8");
const block = wrapper.match(/static const param_def_t PARAMS\[\] = \{([\s\S]*?)\n\};/);
if (!block) { console.error("could not find PARAMS[] in the wrapper"); process.exit(1); }

const params = [];
for (const line of block[1].split("\n")) {
  const m = line.match(
    /\{\s*"([^"]+)"\s*,\s*"[^"]*"\s*,\s*(?:"[^"]*"|NULL)\s*,\s*(K_\w+)\s*,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)/);
  if (m) params.push({ key: m[1], kind: m[2], min: +m[3], max: +m[4], def: +m[5] });
}
if (!params.length) { console.error("PARAMS[] parsed as empty"); process.exit(1); }

/* Presets in a stable order: J-Bass first because it is the closest thing
 * CHONK has to an init patch, then the rest alphabetically. Slot 0 is what a
 * fresh instance loads. */
const dir = join(repo, "src", "presets", "factory");
const files = readdirSync(dir).filter((f) => f.endsWith(".preset")).sort();
const first = "J-Bass.preset";
if (files.includes(first)) files.splice(0, 0, ...files.splice(files.indexOf(first), 1));

const rows = [];
for (const f of files) {
  const pr = JSON.parse(readFileSync(join(dir, f), "utf8"));
  const name = f.replace(/\.preset$/, "");
  const values = params.map((p) => {
    const up = UPSTREAM_NAME[p.key];
    let v = up !== undefined && pr.params && up in pr.params ? pr.params[up] : p.def;
    /* The module narrows two ranges upstream left wide open (Mix Gain's -100
     * dB floor); clamp here so a preset can never carry a value the UI cannot
     * represent or the user cannot get back to. */
    v = Math.min(p.max, Math.max(p.min, v));
    return v;
  });
  const missing = params
    .filter((p) => p.kind !== "K_TOGGLE" && UPSTREAM_NAME[p.key] &&
                   !(UPSTREAM_NAME[p.key] in (pr.params || {})))
    .map((p) => p.key);
  if (missing.length) console.warn(`  ${name}: no upstream value for ${missing.join(", ")} (using defaults)`);
  rows.push({ name, desc: (pr.info && pr.info.Description) || "", values });
}

const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
let out = `/* GENERATED by tools/gen_factory_bank.mjs — do not edit.
 *
 * OneTrick CHONK's ${rows.length} factory sounds (Punk Labs LLC, GPL-3.0-or-later),
 * converted from src/presets/factory/*.preset. Values are in DISPLAY units and
 * in PARAMS[] order; regenerate after any change to PARAMS[] or the .preset
 * files.
 */
#ifndef CHONK_FACTORY_BANK_H
#define CHONK_FACTORY_BANK_H

#define CHONK_FACTORY_PARAMS ${params.length}

typedef struct {
    const char *name;
    const char *desc;
    float value[CHONK_FACTORY_PARAMS];
} chonk_preset_t;

static const chonk_preset_t CHONK_FACTORY[] = {
`;
for (const r of rows) {
  out += `    {"${esc(r.name)}", "${esc(r.desc)}", {\n        `;
  out += r.values.map((v) => (Number.isInteger(v) ? `${v}.0f` : `${v.toFixed(4)}f`)).join(", ");
  out += `\n    }},\n`;
}
out += `};

#define CHONK_FACTORY_COUNT ((int)(sizeof(CHONK_FACTORY) / sizeof(CHONK_FACTORY[0])))

#endif /* CHONK_FACTORY_BANK_H */
`;

writeFileSync(join(repo, "src", "dsp", "factory_bank.h"), out);
console.log(`factory_bank.h: ${rows.length} presets x ${params.length} params`);
